spring:
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    suffix: .html
    prefix: classpath:/templates/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.105.132.96:3306/sohu_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    host: 47.105.132.96

  kafka:
    bootstrap-servers: 47.105.132.96:9092
    consumer:
      auto-offset-reset: earliest
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/department/DepartmentMapper.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  path: log
  level:
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd}--[%thread]--%-5level--%logger{50}--%msg%n"
    file: "%d{yyyy-MM-dd}--[%thread]--%-5level--%logger{50}--%msg%n"







